### ISSUE TITLE
use jQuery instead of HTML DOM functions

### ISSUE THREAD

**Issue by otacke** [otacke/h5p-image-juxtaposition#3]
The code might become a little bit easier to understand when replacing the [original HTML DOM functions of Juxtapose](https://juxtapose.knightlab.com/) with jQuery. There's nothing that's time critical, so we wouldn't have to fear performance issues.

**Comment by falcon-git** [comment]
Do note https://h5ptechnology.atlassian.net/browse/HFP-874

**Comment by otacke** [comment]
Oh, thanks! This will save me some time :-)
