### ISSUE TITLE
Wrong resize when action bar is disabled

### ISSUE THREAD

**Issue by ilukanets** [otacke/h5p-image-juxtaposition#33]
Hi. 
We have an issue with **h5p-image-juxtaposition** object type when action bar is missed.
Iframe is not properly resized and has 0px height. Only window resize helps. Here is a screencast https://take.ms/Ur6pd.
It works fine when action bar is enabled.

Also it could be useful information: On our courses content is rendered after DOM is ready, but calling $(window).trigger('resize') doesn't help.

**Comment by otacke** [comment]
Duplicate to https://github.com/otacke/h5p-image-juxtaposition/issues/24
