### ISSUE TITLE
Issue with image position

### ISSUE THREAD

**Issue by marcvanopstalndla** [otacke/h5p-image-juxtaposition#65]
Images seems to loose the correct overlay position when the screen width changes.
We don't know what is happening and how to avoid this behaviour.
Screenshot and resource examples are attached. 
[mvo-test-4-3-35932_rs.zip](https://github.com/otacke/h5p-image-juxtaposition/files/8263842/mvo-test-4-3-35932_rs.zip)
![2022-03-16 (1)](https://user-images.githubusercontent.com/83448206/158622265-ac616b44-fb0d-4d76-adb4-0b42997b94d4.png)
![2022-03-16](https://user-images.githubusercontent.com/83448206/158622334-65fac2d7-b44b-49bb-83fd-4ee16d78391a.png)

**Comment by otacke** [comment]
@marcvanopstalndla I am not entirely sure why Lumi behaves a little different, but the latest version on the master branch should fix the issue. Please have a look and confirm.

**Comment by otacke** [comment]
@marcvanopstalndla Just found this. Could you please confirm that it is now working as expected for you and in that case close the ticket?

**Comment by marcvanopstalndla** [comment]
this problem has been solved a while ago

**Comment by otacke** [comment]
@marcvanopstalndla Perfect, thanks!
